# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "My awesome app"
    lane :distribute do
        build_app(
            scheme: "Runner",
            export_method: "ad-hoc",
            workspace: "Runner.xcworkspace"
        )

        firebase_app_distribution(
            app: "1:452255726009:ios:c27c29f76fcf27f3689e68",
            release_notes: "Release PH88"
        )

    end

    lane :increment_version do
        latest_release = firebase_app_distribution_get_latest_release(
            app: "1:452255726009:ios:c27c29f76fcf27f3689e68"
        )
        increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
    end
end
