# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
platform :android do
    desc "My awesome app"
    lane :distribute do
        gradle(
  		task: "assemble",
  		build_type: "Release"
	)
        # build_android_app is a built-in fastlane action.
        firebase_app_distribution(
            app: "1:452255726009:android:009d1d6cb4c83575689e68",
            release_notes: "Release beta"
        )
    end
end
